name: "Pre-build TeX Live Dev Container Image"

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜 (UTC)
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: texlive-sci-ja

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.REGISTRY_IMAGE }}
          cacheFrom: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.REGISTRY_IMAGE }}
          subFolder: ./src
          push: always
