name: "Pre-build TeX Live Dev Container Image"

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜 (UTC)
  workflow_dispatch:

env:
  REGISTRY_IMAGE: hisamatsu/texlive-sci-ja

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ${{ env.REGISTRY_IMAGE }}
          platform: linux/amd64,linux/arm64
          subFolder: ./src
          push: always
